Repository f1rzen/IST491, pull requests merged in 2024-04, with the labels that each got.

#1 adding ignored path and files
  .gitignore
Labels: documentation

#3 Lookup
  EDA.ipynb
Labels: enhancement

#6 Kümeleme Analizi ve PCA
  Database/Add_Cluster_Feature.csv
  Database/cancer patient data sets.csv
  Images/PCA_3D.png
  Notebooks/Clustering.ipynb
  Notebooks/Pca.ipynb
Labels: documentation, enhancement
