Repository f1rzen/IST491, pull requests merged in 2024-05, with the labels that each got.

#7 Lookup sklearn
  Notebooks/Logistic_Regression.ipynb
Labels: enhancement

#9 Lookup sklearn
  Notebooks/Logistic_Regression.ipynb
Labels: bug

#11 Streamlit Base Setups
  Streamlit/app.py
  Streamlit/test.ipynb
  requirements.txt
Labels: documentation, enhancement, help wanted

#10 Kmeans n_cluster düzeltmesi
  Database/Add_Cluster_Feature.csv
  Notebooks/Clustering.ipynb
Labels: bug, documentation

#12 Machine learning re
  Models/logistic_regressor_model.pkl
  Notebooks/Machine-learning.ipynb
Labels: documentation, enhancement

#13 Streamlit
  Images/LandingPage.png
  Streamlit/app.py
Labels: documentation, enhancement, help wanted

#14 Streamlit
  .gitignore
  Streamlit/ContactPage/index.html
  Streamlit/ContactPage/style.css
  Streamlit/Pages/__init__.py
  Streamlit/Pages/contact.py
  Streamlit/Pages/dashboard.py
  Streamlit/Pages/dataset.py
  Streamlit/Pages/homepage.py
  Streamlit/Pages/prediction.py
  Streamlit/app.py
  Streamlit/config.toml
Labels: documentation, enhancement, help wanted

#16 Database management
  Database/BaseDataframe.csv
  Database/cancer patient data sets.csv
  Notebooks/EDA.ipynb
Labels: documentation

#17 UI css
  Streamlit/ContactPage/index.html
  Streamlit/ContactPage/style.css
  Streamlit/Pages/contact.py
  Streamlit/app.py
Labels: documentation, enhancement

#22 Issue 19
  Models/theModel.pkl
  Notebooks/Machine-learning.ipynb
Labels: Development

#23 Site pages
  Streamlit/DataPage/index.html
  Streamlit/HomePage/index.html
  Streamlit/Pages/dataset.py
  Streamlit/Pages/homepage.py
  Streamlit/app.py
Labels: Development

#25 Streamlit prediction page
  Images/GaussianNB_feature_importance.png
  Models/logistic_regressor_model.pkl
  Models/theModel.pkl
  Streamlit/Encoders/encoder.pkl
  Streamlit/Model/logistic_regressor_model.pkl
  Streamlit/Model/theModel.pkl
  Streamlit/Pages/prediction.py
  Streamlit/PredictionPage/ML_FeatureImportance.ipynb
  Streamlit/PredictionPage/col1_page.html
  Streamlit/PredictionPage/col2_page.html
  Streamlit/PredictionPage/info_card.html
  Streamlit/PredictionPage/metric_cards.html
  Streamlit/app.py
  Streamlit/config.toml
Labels: documentation, Development

#26 Visualization page
  Streamlit/Pages/visualization.py
  Streamlit/app.py
Labels: Development

#27 Add Images to README
  Images/contact.png
  Images/dataset.png
  Images/homepage.png
  Images/prediction-1.png
  Images/prediction-2.png
  Images/visualization.png
  README.md
Labels: documentation

#28 ui and form fixes
  Streamlit/ContactPage/index.html
  Streamlit/HomePage/index.html
  Streamlit/app.py
Labels: Streamlit
